[package]
name = "rboy"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true

[dependencies]
log = "0.4.19"
pretty_env_logger = "0.5.0"
simplelog = "0.12.1"
